### ISSUE TITLE
made a deb

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/chromium86#1]
## to uninstall it:
`sudo apt purge chromium-rpi`

## instructions to make it again:
1). download the zip and unzip it to a folder called chromium86 (folder name doesn't really matter).

2a. open terminal and run:
```bash
cd path/to/chromium86
mkdir DEBIAN
cd DEBIAN
```
2b. create a file inside the DEBIAN folder called `control`, and give it 775 permissions by running `sudo chmod 775 control`
insert the following text into it, change version, maintainer and description (and more if you know what you are doing):
```
Maintainer: your-name and email/link/whatever you want
Summary: Chromium v86 for the raspberry pi (includes all of the RPi foundation's mods).
Name:chromium-rpi
Description: Chromium86 for the RaspberryPi
Version: 1:86-1
Release: 1 
License: GPL 
Architecture: armhf
Provides: chromium-rpi
Priority: optional
Section: custom
Conflicts: chromium-browser
Package: chromium-rpi
```
3a. create a file inside the DEBIAN folder called `preinst` and give it 775 permissions.
3b. enter the following script inside it:
```bash#!/bin/bash

while true; do
	echo -e "\e[1m\e[31mWARNING: your current chromium will be uninstalled!\nare you sure you want to proceed (y/N)?\e[0m"
	read answer
if [[ "$answer" =~ [yY] ]]; then
	echo "OK, continuing..."
	break
elif [[ "$answer" =~ [nN] ]]; then
	echo "OK, exiting..."
	exit 1
else
	echo -e "\e[31minvalid option '$answer', please try again.\e[0m"
fi
done
```
this will make sure the user wants to install this deb and replace the existing chromium.

5. run `cd ../../`
6. run `dpkg-deb -b chromium86/ chromium86_armhf.deb` but change the name at the end to whatever you want/need.
`-b` = `--build`
you might need to install `dpkg-dev`.

**Comment by Itai-Nelken** [comment]
the deb: https://app.box.com/s/hmmsi2v8ber2yinzlwnk4ywiet6eqhiv

**Comment by Botspot** [comment]
Wow. You are too proactive! :)

Actually, I wasn't even planning on doing anything with this repo. I saw Chromium-browser was being upgraded today, and realized that there may well be bugs or drawbacks. So I archived my existing install for my own benefit.

Then I chose to upload it to github, so that if there were severe Chromium bugs, it would be ready and waiting for anyone to use as a quick-fix.

As of now, there are no plans to put it on Pi-Apps, but as I said above, if the new chromium version has bugs, everything will already be laid out, and the only thing to do would be to upload "Back to Chromium v86" to Pi-Apps.

Thanks for the tutorial, by the way. :)

**Comment by Itai-Nelken** [comment]
I didn't make it for pi-apps, just thought it could be added to the releases page if someone ever wants it. also I made it because when I opened the unzipped folder to see what is inside I saw that the file structure (if thats how you say it) is the same as the one in a deb.
slightly of topic: what do you think the rpi foundation will do once google remove sync and other google API's from chromium (in a few days I think)? switch to firefox? use degoogled chromium? use the existing chromium but without sync and stuff?

**Comment by Botspot** [comment]
> slightly of topic: what do you think the rpi foundation will do once google remove sync and other google API's from chromium (in a few days I think)? switch to firefox? use degoogled chromium? use the existing chromium but without sync and stuff?

What the _Foundation_ will do? Probably nothing.  
What the _community_ will do? Huge uproar.

In the event that Chromium v86 or Chromium v78 still supports Chrome sync after March 15th, I'll be prepared. ;)

If that doesn't work, then I expect that someone, somewhere will come up with a solution. Possible outcomes I can see:

- Google may release arm Chrome.
- Or, some coder may find a sneaky way to circumvent the rule and re-enable Chrome sync. Maybe by using a Chromebook OS user-agent. (I'm going to try that)
- If all else fails, there will probably be a couple 3rd-party syncing solutions, that use Google Drive or Dropbox, to sync portions of `~/.config.chromium`. If I wasn't working on UltiFlash right now, I'd be working on Cloud Buddy, a GUI app that would make use of `rclone` and allow for easy setup of mounted shares and regular file-syncing.

Too bad there isn't an army of Botspots. Or an army of Itais... XD

**Comment by Botspot** [comment]
Now it's in the releases page. BTW, how did you shrink the deb even more than my zip was?
My zip is over 100MB, but your deb is less than 100MB.

**Comment by Itai-Nelken** [comment]
> Now it's in the releases page. BTW, how did you shrink the deb even more than my zip was?
> My zip is over 100MB, but your deb is less than 100MB.

`dpkg-deb` compresses it as a `tar.xz` so maybe its that? 
<img width="341" alt="Screen Shot 2021-03-11 at 8 12 23 PM" src="https://user-images.githubusercontent.com/70802936/110834344-1c8b3800-82a6-11eb-8568-31b1b680eaef.png">
that is the contrents of the deb, and `data.tar.xz` is 104mb, so mostly all th size of the deb.

**Comment by Itai-Nelken** [comment]
>Too bad there isn't an army of Botspots. Or an army of Itais... XD

 🤣

**Comment by Botspot** [comment]
Hey @Itai-Nelken, would you be willing to make a couple debs for various common versions of Mesa?

https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=304078

**Comment by Itai-Nelken** [comment]
compile mesa and make a deb? yes, I can (using checkinstall probably)
but i have no idea how to make it to separate packages..

**Comment by Itai-Nelken** [comment]
also thanks for your thoughts on google removing sync from chromium.

**Comment by Itai-Nelken** [comment]
I asked the same question in the rpi forums: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=306590

**Comment by Botspot** [comment]
> compile mesa and make a deb? yes, I can (using checkinstall probably)
> but i have no idea how to make it to separate packages..

Well you could compile mesa several times, and make several packages all named `mesa`. I don't care for a repository - pi-apps could simply download a different URL to switch versions.

**Comment by Botspot** [comment]
> I asked the same question in the rpi forums: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=306590

Ehh... You're welcome to do that, but don't expect those people to represent the RPi community as a whole. Those guys didn't appreciate Pi-Apps much either, saying the "terminal was easier" or whatever.

**Comment by Itai-Nelken** [comment]
so 20.2 and 20.3 is ok?
>Ehh... You're welcome to do that, but don't expect those people to represent the RPi community as a whole. Those guys didn't appreciate Pi-Apps much either, saying the "terminal was easier" or whatever.

I understood that pretty fast.. anyway its interesting to see what people think, most of them said something like `why do you even need sync?`.

**Comment by Botspot** [comment]
> I understood that pretty fast.. anyway its interesting to see what people think, most of them said something like `why do you even need sync?`.

Exactly.

> so 20.2 and 20.3 is ok?

Sounds good. 20.2, 20.3, and whatever-the-most-cutting-edge-version-there-is.

**Comment by Itai-Nelken** [comment]
so 20.2, 20.3 and 21.0.

## notes mainly for me
#### compilation:
dependencies:
```bash
sudo apt purge meson -y && sudo apt install python3-pip && pip3 install meson
```
(there are more)

```bash
git clone https://gitlab.freedesktop.org/mesa/mesa
cd mesa
git checkout 20.2
mkdir build
meson --prefix /usr -Dplatforms=x11 -Dvulkan-drivers= -Ddri-drivers= -Dgallium-drivers=v3d,kmsro,vc4,virgl -Dbuildtype=release build
ninja -C build
sudo ninja -C build install 
```

**Comment by Itai-Nelken** [comment]
@Botspot can you add to the release that to uninstall the deb you have to run `sudo apt purge chromium-rpi` or that the package name is `chromium-rpi`?

**Comment by Botspot** [comment]
> @Botspot can you add to the release that to uninstall the deb you have to run `sudo apt purge chromium-rpi` or that the package name is `chromium-rpi`?

Done.

**Comment by Itai-Nelken** [comment]
I don't think I'll ever come round to making the mesa debs :( sorry.
if it helps, here is `ninja`'s output:
[ninja-install-output-mesa.txt](https://github.com/Botspot/chromium86/files/6316559/ninja-install-output-mesa.txt)
all the files it copies have to be put in a list and then copied into a .deb, that's what I'm meaning to do.
if someone can help simplifying the list, it would help a lot and I could make the debs.
example for simplifying:
from this line: 
`Installing src/mapi/shared-glapi/libglapi.so.0.0.0 to /usr/lib/arm-linux-gnueabihf`
to this: `/usr/lib/arm-linux-gnueabihf/libglapi.so.0.0.0`

I'm pretty sure a simple bash script could do that, but I have no idea how.

the output might be different between different versions of mesa, that output is from 20.2 if I remember correctly.
